baseURL: "https://archit15singh.github.io/"
languageCode: "en-us"
title: "Archit's Space"
pagination:
  pagerSize: 10
theme: hugo-PaperMod

params:
  # General Settings
  DateFormat: "January 2, 2006"
  env: production
  description: "Building Systems from First Principles: AI, Cognitive Science, and Engineering Deep Dives by Archit Singh"
  author: "Archit Singh"
  defaultTheme: auto
  comments: false
  disableScrollToTop: true
  image_format: "webp"
  goatcounter: "architsingh"

  # SEO Settings
  metaDescription: "Archit Singh’s blog on first-principles systems thinking—covering AI agent architectures, cognitive science, and resilient engineering."
  canonicalURL: "https://archit15singh.github.io/"

  # Display Settings
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  images: ["papermod-cover.png"]

  # Features
  ShowShareButtons: true

  # Profile Mode
  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"

  # Home Info
  homeInfoParams:
    Title: "Building Systems from First Principles"
    Content: >
      I’m Archit Singh—a backend engineer, AI-agent architect, and lifelong systems thinker. I refuse to settle for surface-level explanations. Instead, I dig down to first principles, model complex ideas across disciplines, and iterate obsessively until clarity yields impact. From epistemology and symbolic systems to resilient data pipelines and memory-augmented AI, this space shares high-signal, first-principles deep dives.

  # Social Icons
  socialIcons:
    - name: github
      url: "https://github.com/archit15singh"
    - name: linkedin
      url: "https://www.linkedin.com/in/archit15singh"
    - name: twitter
      url: "https://x.com/archit_singh15"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/6245870/archit-singh"
    - name: Rss
      url: "index.xml"

  # Assets
  assets:
    disableHLJS: true
    disableFingerprinting: false

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

sitemap:
  changefreq: "weekly"
  priority: 0.5
  filename: "sitemap.xml"

minify:
  disableXML: true
  minifyOutput: true
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true
  x:
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
