blank_issues_enabled: false
contact_links:
  - name: PaperMod Discussions
    url: https://github.com/archit15singh/discussions
    about: Please ask and answer questions/doubts here, do not open an issue for questions.
